spring.profiles.active=${environmentName:local}
spring.application.name=notification-service
app.name=zea-2026-b02-nischay-ride-booking-notification-service
app=${spring.application.name}

server.port=8080

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

atropos.publish.mode=KINESIS

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api/v1/ui

# Resend email configuration (prefer env vars for secrets)
resend.api.key=enc:KjVVodU1yuEYmeStS9TWAEEcq51BMlGDztpnTywjqZj4QvgEh57R3MJpCX/0QcgsOs4A3G0oZRWbBHChD6yzwA==
resend.from.email=enc:2CcbdmGEqyzGZvXOJEpfLOZbbdBtvNFf8wuE6E+EohpNxnI7V/fxuGPnTTIHW6JhZGJ/4rCLwos1tI9Cxsmv+n8DaSCsIy3t
resend.default.to=${RESEND_DEFAULT_TO:nischayhr11@gmail.com}
resend.crypto.passphrase=Nischay1

# Twilio SMS configuration
twilio.account.sid=enc:OD1aa6bakef8CW/XV3eaK5J/f7/7SGeueUg1biHdG0f2N9piS4/ebK/39nNjFox/CxuJzqNDrFOibUdcrCU=
twilio.auth.token=enc:aNziPjvzj9azcUmX1GBLnNTI0vQ95xr77C4UjtPiFzViUsrnNElsDhVpc7L2Th6B99uC6M4B1TuTvdHL
twilio.from.number=enc:UhhW+/qz1tp4BHRaSz1NKUk3SDOeFUYDYXe1ILHqRdEngg7yLhIwrA==
twilio.default.to=${TWILIO_DEFAULT_TO:+919448048720}

management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.health=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
spring.health.endpoint.path=/health