spring.profiles.active=${environmentName:local}
spring.application.name=driver-service
app.name=zea-2026-b02-nischay-ride-booking-driver-service
app=${spring.application.name}

server.port=8080

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

atropos.publish.mode=KINESIS

#cipher 
#cipher 
certstore.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
sessions.proteus.endpoint=https://sb1-god-cipher.mum1-pp.zetaapps.in/proteus/zeta.in
proteus.endpoint=https://api.stage.zeta.in/zeta.in

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/api/v1/ui

management.endpoints.web.base-path=/actuator
management.endpoints.web.path-mapping.health=health
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
spring.health.endpoint.path=/health
