app.name=zea-2026-b02-nischay-ride-booking-ride-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ride_booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
atropos.publish.mode=KINESIS
